### ISSUE TITLE
Fix adding subtasks

### ISSUE THREAD

**Issue by Undeadlol1** [Undeadlol1/flow-todo#2]
- [x] CreateSubtask
- [x] Decrease complexity of TaskPage
- [x] (?) SubtasksList
- [x] Show subtask.name in title if task has subtasks
- [x] Indicate somehow that subtask is active
- [x] "done" button must consider isTask/isSubtask context
- [x] arrange items properly and make sure responsivnes works
